[project]
org-name = "hemikak"
version = "0.0.4"
authors = ["hemika.kodikara@gmail.com"]
repository = "https://github.com/hemikak/ballerina-string-utils"
keywords = ["ballerina", "string", "utility", "utils"]
license = "Apache-2.0"
